"""Synonym label maps per report type / schema field."""

from __future__ import annotations

CBC_SYNONYMS: dict[str, list[str]] = {
    "facility": ["Facility", "Hospital", "Laboratory", "Lab Name", "Institution"],
    "report_title": ["Report Title", "Test Name", "Panel", "CBC", "Complete Blood Count"],
    "patient_name": ["Patient Name", "Patient", "Name", "Pt Name"],
    "mrn": ["MRN", "Medical Record Number", "Medical Record No", "File No", "Patient ID"],
    "age_years": ["Age", "Age (Years)", "Age Years"],
    "test_id": ["Test ID", "Accession", "Sample ID", "Lab Number", "Order No"],
    "test_date": ["Test Date", "Collection Date", "Date Collected", "Report Date", "Date"],
    "nucleated_rbc": ["Nucleated RBC", "nRBC", "NRBC"],
    "wbc": ["WBC", "White Blood Cell", "White Blood Cells", "Leukocyte", "Leukocytes", "WBC Count"],
    "rbc": ["RBC", "Red Blood Cell", "Red Blood Cells", "Erythrocyte", "Erythrocytes"],
    "hemoglobin": ["Hemoglobin", "Haemoglobin", "Hgb", "Hb", "HGB"],
    "hematocrit": ["Hematocrit", "Haematocrit", "Hct", "HCT", "PCV"],
    "mchc": ["MCHC"],
    "lymphocytes_abs": ["Lymphocytes Abs", "Lymphocyte Absolute", "Lymphocytes Absolute", "Lymph Abs"],
    "platelets": ["Platelets", "Platelet", "PLT", "Platelet Count"],
    "neutrophils_abs": ["Neutrophils Abs", "Neutrophil Absolute", "Neutrophils Absolute", "Neut Abs"],
    "monocytes_abs": ["Monocytes Abs", "Monocyte Absolute", "Monocytes Absolute", "Mono Abs"],
    "eosinophils_abs": ["Eosinophils Abs", "Eosinophil Absolute", "Eosinophils Absolute", "Eos Abs"],
    "basophils_abs": ["Basophils Abs", "Basophil Absolute", "Basophils Absolute", "Baso Abs"],
}

ECHO_SYNONYMS: dict[str, list[str]] = {
    "facility": ["Facility", "Hospital", "Institution"],
    "department": ["Department", "Dept", "Cardiology"],
    "address": ["Address", "Location"],
    "report_title": ["Report Title", "Study", "Echocardiogram", "Transthoracic Echo"],
    "patient_name": ["Patient Name", "Patient", "Name"],
    "mrn": ["MRN", "Medical Record Number", "Medical Record No", "File No"],
    "date_of_birth": ["Date of Birth", "DOB", "Birth Date"],
    "age_years": ["Age", "Age (Years)"],
    "sex": ["Sex", "Gender"],
    "bsa_m2": ["BSA", "Body Surface Area"],
    "bmi": ["BMI", "Body Mass Index"],
    "referring_physician": ["Referring Physician", "Referring Doctor", "Referred By", "Physician"],
    "indication": ["Indication", "Clinical Indication", "Reason for Study"],
    "study_date": ["Study Date", "Exam Date", "Date of Study", "Procedure Date"],
    "report_date": ["Report Date", "Date Reported"],
    "lvedd_mm": ["LVEDD", "LV End Diastolic Dimension", "LVIDd"],
    "lvesd_mm": ["LVESD", "LV End Systolic Dimension", "LVIDs"],
    "ivsd_mm": ["IVSd", "IVS", "Interventricular Septum"],
    "pwd_mm": ["PWd", "PW", "Posterior Wall"],
    "ef_percent": ["EF", "Ejection Fraction", "LVEF", "EF %"],
    "lv_mass_index": ["LV Mass Index", "LVMI"],
    "la_diameter_mm": ["LA Diameter", "Left Atrium Diameter", "LA Size"],
    "la_volume_index": ["LA Volume Index", "LAVI"],
    "ea_ratio": ["E/A", "E/A Ratio", "EA Ratio"],
    "ee_prime_lateral": ["E/E'", "E/e'", "E/E lateral", "Ee prime"],
    "deceleration_time_ms": ["Deceleration Time", "DT", "Decel Time"],
    "tapse_mm": ["TAPSE"],
    "rvsp_mmhg": ["RVSP", "Right Ventricular Systolic Pressure"],
    "aortic_root_mm": ["Aortic Root", "Ao Root"],
    "clinical_correlation": ["Clinical Correlation", "Correlation"],
    "signed_by": ["Signed By", "Reported By", "Cardiologist", "Physician Signature"],
    "report_id": ["Report ID", "Report No", "Document ID"],
}

RADIOLOGY_SYNONYMS: dict[str, list[str]] = {
    "facility": ["Facility", "Hospital", "Institution"],
    "report_type": ["Report Type", "Modality", "Exam Type"],
    "mrn": ["MRN", "Medical Record Number", "Medical Record No", "File No"],
    "patient_name": ["Patient Name", "Patient", "Name"],
    "referring_dept": ["Referring Dept", "Referring Department", "Department"],
    "referral_date": ["Referral Date", "Order Date"],
    "test_time": ["Test Time", "Exam Time", "Study Time", "Performed"],
    "interpretation_time": ["Interpretation Time", "Reported Time", "Dictated"],
    "clinical_dx": ["Clinical Dx", "Clinical Diagnosis", "Diagnosis"],
    "test_name": ["Test Name", "Procedure", "Exam Name"],
    "position": ["Position", "View", "Projection"],
    "exam_title": ["Exam Title", "Title", "Examination"],
    "clinical_indication": ["Clinical Indication", "Indication", "Reason"],
    "comparison": ["Comparison", "Compared To", "Prior Study"],
    "findings": ["Findings", "FINDINGS", "Observation"],
    "cardiothoracic_ratio": ["Cardiothoracic Ratio", "CTR", "CT Ratio"],
    "cardiothoracic_ratio_prior": ["Prior CTR", "Previous Cardiothoracic Ratio", "CTR Prior"],
    "resident_radiologist": ["Resident Radiologist", "Resident", "Radiology Resident"],
    "consultant_radiologist": ["Consultant Radiologist", "Consultant", "Radiologist"],
    "printed_by": ["Printed By", "Print User"],
    "print_datetime": ["Print Date", "Print Datetime", "Printed On"],
    "page": ["Page"],
}

ULTRASOUND_SYNONYMS: dict[str, list[str]] = {
    "facility": ["Facility", "Hospital", "Institution"],
    "department": ["Department", "Dept"],
    "address": ["Address", "Location"],
    "patient_name": ["Patient Name", "Patient", "Name"],
    "mrn": ["MRN", "Medical Record Number", "Medical Record No", "File No"],
    "date_of_birth": ["Date of Birth", "DOB", "Birth Date"],
    "age_years": ["Age", "Age (Years)"],
    "gender": ["Gender", "Sex"],
    "referring_physician": ["Referring Physician", "Referring Doctor", "Referred By"],
    "referring_department": ["Referring Department", "Referring Dept"],
    "exam_date": ["Exam Date", "Study Date", "Examination Date", "Scan Date"],
    "report_date": ["Report Date", "Date Reported"],
    "clinical_indication": ["Clinical Indication", "Indication", "Reason"],
    "indication_creatinine": ["Creatinine", "Cr", "Serum Creatinine"],
    "indication_egfr": ["eGFR", "EGFR", "GFR"],
    "indication_acr": ["ACR", "Albumin Creatinine Ratio"],
    "technique": ["Technique", "Method", "Protocol"],
    "comparison": ["Comparison", "Compared To"],
    "right_kidney": ["Right Kidney", "RT Kidney", "Right Renal"],
    "left_kidney": ["Left Kidney", "LT Kidney", "Left Renal"],
    "renal_doppler": ["Renal Doppler", "Doppler"],
    "urinary_bladder": ["Urinary Bladder", "Bladder"],
    "recommendation": ["Recommendation", "Advice", "Follow Up"],
    "radiologist": ["Radiologist", "Reported By", "Signed By"],
    "report_id": ["Report ID", "Report No", "Document ID"],
}
