"""Synonym label maps per report type / schema field."""

from __future__ import annotations

# Exact KAUH-style CBC labels only (plus known OCR/typo variants).
# Prefer full strings so % vs K/uL and MCH vs MCHC do not collide.
CBC_SYNONYMS: dict[str, list[str]] = {
    "patient_name": ["Name", "Patient Name", "Patient"],
    "age_years": ["Age", "Age (Years)", "Age Years"],
    "test_id": ["Test", "Test ID", "Test No", "Test Number"],
    "test_date": ["Test Date", "Date"],
    "nucleated_rbc": [
        "Automated Neucleated RBC K/uL",
        "Automated Nucleated RBC K/uL",
        "Automated Neucleated RBC",
        "Automated Nucleated RBC",
        "Nucleated RBC",
        "nRBC",
        "NRBC",
    ],
    "wbc": [
        "White Blood Cell Count (WBC)",
        "White Blood Cell Count",
        "WBC",
    ],
    "rbc": [
        "Red Blood cell count (RBC)-c",
        "Red Blood Cell Count (RBC)-c",
        "Red Blood cell count (RBC)",
        "Red Blood Cell Count (RBC)",
        "Red Blood Cell Count",
        "RBC",
    ],
    "hemoglobin": [
        "Hemoglobin (Hb)",
        "Haemoglobin (Hb)",
        "Hemoglobin",
        "Haemoglobin",
        "Hb",
        "Hgb",
    ],
    "hematocrit": [
        "Hematocrit (HCT)-",
        "Hematocrit (HCT)",
        "Haematocrit (HCT)",
        "Hematocrit",
        "Haematocrit",
        "HCT",
    ],
    "mchc": [
        "Mean Cell Hemoglobin Concentration (MCHC)",
        "Mean Cell Haemoglobin Concentration (MCHC)",
        "MCHC",
    ],
    "lymphocytes_abs": [
        "Automated Lymphocytes K/ul",
        "Automated Lymphocytes K/uL",
        "Automated Lymphocytes Abs",
    ],
    "mcv": [
        "Mean Cell Volume (MCV)",
        "MCV",
    ],
    "platelets": [
        "Platelets Count (PLT)-",
        "Platelets Count (PLT)",
        "Platelet Count (PLT)",
        "Platelets Count",
        "Platelet Count",
        "PLT",
    ],
    "monocytes_pct": [
        "Automated Monocytes (%)",
        "Automated Monocytes %",
    ],
    "eosinophils_pct": [
        "Automated Eosinophils (%)",
        "Automated Eosinophils %",
    ],
    "neutrophils_abs": [
        "Automated Neutrophils K/uL",
        "Automated Neutrophils K/ul",
        "Automated Neutrophils Abs",
    ],
    "monocytes_abs": [
        "Automated Monocytes K/uL",
        "Automated Monocytes K/ul",
        "Automated Monocytes Abs",
    ],
    "eosinophils_abs": [
        "Automated Eosinophils K/uL",
        "Automated Eosinophils K/ul",
        "Automated Eosinophils Abs",
    ],
    "mch": [
        "Mean Cell Hemoglobin (MCH)",
        "Mean Cell Haemoglobin (MCH)",
        "MCH",
    ],
    "lymphocytes_pct": [
        "Automated Lymphocytes (%)",
        "Automated Lymphocytes %",
    ],
    "pdw": [
        "Platelet Volume Width (PDW)",
        "PDW",
    ],
    "pct": [
        "Plateletcrit (PCT)",
        "Plateletcrit",
        "PCT",
    ],
    "neutrophils_pct": [
        "Automated Neutrophils (%)",
        "Automated Neutrophils %",
    ],
    "rdw_cv": [
        "Red Cell Distribution Width (RDW-CV)",
        "RDW-CV",
        "RDW CV",
        "RDW",
    ],
    "p_lcr": [
        "Platelet- Large Cell Ratio (P-LCR)",
        "Platelet Large Cell Ratio (P-LCR)",
        "Platelet-Large Cell Ratio (P-LCR)",
        "P-LCR",
        "PLCR",
    ],
    "ig_pct": [
        "Automated Immature Granulocytes(IG)(%)",
        "Automated Immature Granulocytes (IG)(%)",
        "Automated Immature Granulocytes(IG) %",
        "Automated Immature Granulocytes (IG) %",
        "IG (%)",
    ],
    "ig_abs": [
        "Automated Immature Granulocytes(IG) K/uL",
        "Automated Immature Granulocytes (IG) K/uL",
        "Automated Immature Granulocytes(IG) K/ul",
        "Automated Immature Granulocytes (IG) K/ul",
        "IG K/uL",
        "IG K/ul",
    ],
    "basophils_pct": [
        "Automated Basophils (%)",
        "Automated Basophils %",
    ],
    "basophils_abs": [
        "Automated Basophils K/uL",
        "Automated Basophils K/ul",
        "Automated Basophils Abs",
    ],
    "mpv": [
        "Mean Platelet Volume (MPV)",
        "MPV",
    ],
}

ECHO_SYNONYMS: dict[str, list[str]] = {
    "facility": ["Dr. Soliman Fakeeh Hospital", "Facility", "Hospital"],
    "department": [
        "Cardiology Department — Echocardiography Laboratory",
        "Cardiology Department",
        "Echocardiography Laboratory",
        "Department",
    ],
    "report_title": [
        "TRANSTHORACIC ECHOCARDIOGRAM REPORT",
        "Transthoracic Echocardiogram Report",
        "Echocardiogram Report",
    ],
    "patient_name": ["Patient", "Patient Name", "Name"],
    "mrn": ["MRN", "Medical Record Number", "Medical Record No"],
    "date_of_birth": ["DOB", "Date of Birth", "Birth Date"],
    "age_years": ["Age"],
    "sex": ["Sex", "Gender"],
    "bsa_m2": ["BSA", "Body Surface Area"],
    "bmi": ["BMI", "Body Mass Index"],
    "referring_physician": [
        "Referring",
        "Referring Physician",
        "Referring Doctor",
        "Referred By",
    ],
    "indication": ["Indication", "Clinical Indication"],
    "study_date": ["Study Date", "Exam Date", "Date of Study"],
    "report_date": ["Report Date", "Date Reported"],
    "lvedd_mm": [
        "LV End-Diastolic Diameter (LVEDd)",
        "LV End-Diastolic Diameter",
        "LVEDd",
        "LVEDD",
    ],
    "lvesd_mm": [
        "LV End-Systolic Diameter (LVESd)",
        "LV End-Systolic Diameter",
        "LVESd",
        "LVESD",
    ],
    "ivsd_mm": [
        "Interventricular Septum (IVSd)",
        "Interventricular Septum",
        "IVSd",
        "IVS",
    ],
    "pwd_mm": [
        "Posterior Wall Thickness (PWd)",
        "Posterior Wall Thickness",
        "PWd",
        "PW",
    ],
    "ef_percent": [
        "LV Ejection Fraction (EF)",
        "LV Ejection Fraction",
        "Ejection Fraction",
        "LVEF",
        "EF",
    ],
    "lv_mass_index": ["LV Mass Index", "LVMI"],
    "la_diameter_mm": [
        "Left Atrial Diameter",
        "LA Diameter",
        "Left Atrium Diameter",
    ],
    "la_volume_index": [
        "Left Atrial Volume Index",
        "LA Volume Index",
        "LAVI",
    ],
    "ea_ratio": ["E/A Ratio", "E/A", "EA Ratio"],
    "ee_prime_lateral": [
        "E/e' Ratio (Lateral)",
        "E/e' Ratio",
        "E/E' Ratio (Lateral)",
        "E/e'",
        "E/E'",
    ],
    "deceleration_time_ms": ["Deceleration Time", "DT"],
    "tapse_mm": ["TAPSE"],
    "rvsp_mmhg": [
        "RV Systolic Pressure (est.)",
        "RV Systolic Pressure",
        "RVSP",
        "Right Ventricular Systolic Pressure",
    ],
    "aortic_root_mm": ["Aortic Root", "Ao Root"],
    "clinical_correlation": ["Clinical Correlation"],
    "signed_by": ["Signed By", "Reported By"],
    "report_id": ["Report ID", "Report No"],
}

RADIOLOGY_SYNONYMS: dict[str, list[str]] = {
    "facility": [
        "King Abdulaziz University Hospital",
        "Facility",
        "Hospital",
    ],
    "report_type": ["Radiology Test", "Report Type", "Modality"],
    "mrn": ["MRN", "MFRN", "Medical Record Number", "Medical Record No"],
    "patient_name": ["Name", "Patient Name", "Patient"],
    "referring_dept": [
        "Dept/Ward (Referred from)",
        "Dept/Ward",
        "Referring Dept",
        "Referring Department",
        "Referred from",
    ],
    "referral_date": [
        "Referral Date",
        "Referral Dato",
        "Roterol Date",
        "Rotera Date",
        "Order Date",
    ],
    "test_time": ["Test Time", "Tost Time", "Exam Time", "Study Time"],
    "interpretation_time": [
        "Interpretation Time",
        "Reported Time",
        "Dictated",
    ],
    "clinical_dx": [
        "Clinical Dx",
        "Clinical Dx.",
        "Glinical Dx",
        "Clinical Diagnosis",
        "Medical History and Clinical Dx",
        "Medical History and Clinical Ox",
    ],
    "test_name": ["Test Name", "Procedure", "Exam Name"],
    "position": ["Position/Type", "Position/Tyr/el", "Position", "View", "Projection"],
    "exam_title": [
        "CHEST X-RAY PA AND LATERAL",
        "Conclusion",
        "Exam Title",
    ],
    "clinical_indication": ["CLINICAL INDICATION", "Clinical Indication", "Indication"],
    "comparison": ["COMPARISON", "Comparison", "Compared To"],
    "findings": ["FINDINGS", "Findings"],
    "cardiothoracic_ratio": [
        "cardiothoracic ratio",
        "Cardiothoracic Ratio",
        "CTR",
        ".rdiothoracic ratio",
    ],
    "cardiothoracic_ratio_prior": [
        "previously",
        "Prior CTR",
        "previous",
    ],
    "resident_radiologist": [
        "RESIDENT RADIOLOGIST",
        "Resident Radiologist",
        "Resident",
    ],
    "consultant_radiologist": [
        "CONSULTANT RADIOLOGIST",
        "Consultant Radiologist",
        "Consultant",
    ],
    "printed_by": ["Printed by", "Printed By", "Print User"],
    "print_datetime": ["Print Date", "Print Datetime", "Printed On"],
    "page": ["Page"],
}

ULTRASOUND_SYNONYMS: dict[str, list[str]] = {
    "facility": [
        "Saudi German Hospital - Jeddah",
        "Saudi German Hospital",
        "Facility",
        "Hospital",
    ],
    "department": ["Department of Radiology", "Department of Radiology"],
    "address": [
        "Al Madinah Al Munawwarah Road, Jeddah 21461, Kingdom of Saudi Arabia",
        "Address",
    ],
    "patient_name": ["Patient Name", "Patient", "Name"],
    "mrn": ["MRN", "Medical Record Number", "Medical Record No"],
    "date_of_birth": ["DOB", "Date of Birth", "Birth Date"],
    "age_years": ["Age"],
    "gender": ["Gender", "Sex"],
    "referring_physician": [
        "Referring Physician",
        "Referring Doctor",
        "Referred By",
    ],
    "referring_department": ["Department"],
    "exam_date": ["Exam Date", "Study Date", "Examination Date", "Scan Date"],
    "report_date": ["Report Date", "Date Reported"],
    "clinical_indication": ["Clinical Indication", "Indication"],
    "indication_creatinine": ["creatinine", "Creatinine", "Serum Creatinine"],
    "indication_egfr": ["eGFR", "EGFR", "reduced eGFR"],
    "indication_acr": ["ACR", "Albumin Creatinine Ratio", "microalbuminuria (ACR"],
    "technique": ["Technique"],
    "comparison": ["Comparison"],
    "right_kidney": ["Right Kidney"],
    "left_kidney": ["Left Kidney"],
    "renal_doppler": ["Renal Doppler"],
    "urinary_bladder": ["Urinary Bladder"],
    "recommendation": ["Recommendation"],
    "radiologist": ["Radiologist", "Consultant Radiologist", "Reported By", "Signed By"],
    "report_id": ["Report ID", "Report No"],
}
